---
title: "Data_Science"
output: html_document
date: "2022-09-10"
---

```{r}
rm(list=ls())
library(readr)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(gganimate)
library(corrplot)
library(ggcorrplot)

# devtools::install_github("thomasp85/gganimate", ref="v0.1.1")
# remotes::install_github("thomasp85/gganimate@v0.1.1")
ds_df <- read.csv("ds_salaries.csv", stringsAsFactors = T)[,-1]
```


### EDA

#### Salary Distributions

```{r}
salaries_df <- ds_df %>% 
  filter (company_size == "L") %>% 
  group_by(job_title) %>% 
  summarise(salary = mean(salary_in_usd),
            n = n()) %>% 
  arrange(desc(salary)) %>% 
  filter(n >= 5)

salaries_df
```

```{r}
##________By Title____________
salaries_df <- ds_df %>% 
  group_by(job_title) %>% 
  summarise(salary = mean(salary_in_usd),
            n = n()) %>% 
  arrange(desc(salary)) %>% 
  filter(n >= 15)

salaries_df <- salaries_df[1:5,-3]
salaries_df
salaries_df$t <- c(1,1,2,2,3)

by_title_p <- ggplot(salaries_df, aes(x = job_title, y = salary, fill = salary, frame = t)) +
  geom_bar(stat = "identity",
           lwd = 1, show.legend = T) +
  ggtitle("Pay by Job Title") +
  coord_polar() + 
  theme_minimal()
plot(by_title_p)


leaders_df <- ds_df %>% 
  group_by(job_title) %>% 
  summarise(salary = mean(salary_in_usd),
            n = n()) %>% 
  arrange(desc(salary)) %>% 
  filter(n >= 5)
leaders_df

leaders_df <- leaders_df[1:5,-3]

by_leader_p <- ggplot(leaders_df, aes(x = job_title, y = salary, fill = salary)) +
  geom_bar(stat = "identity",
           lwd = 1, show.legend = T) +
  ggtitle("Pay by Job Title") +
  coord_polar() + 
  theme_minimal()
by_leader_p

##________By Experience___________
exp_df <- ds_df %>% 
  group_by(experience_level) %>% 
  summarise(salary = mean(salary_in_usd),
            n = n()) %>% 
  arrange(desc(salary)) %>% 
  filter(n >= 10)

by_exp_p <- ggplot(exp_df, aes(x = experience_level, y = salary, fill = salary)) +
  geom_bar(stat = "identity",
           lwd = 1, show.legend = T) +
  ggtitle("Pay by Experience") +
  coord_polar() + 
  theme_minimal()
by_exp_p


##________By Location___________
loc_df <- ds_df %>% 
  group_by(company_location) %>% 
  summarise(salary = mean(salary_in_usd),
            n = n()) %>% 
  arrange(desc(salary)) %>% 
  filter(n >= 10)

by_loc_p <- ggplot(loc_df, aes(x = company_location, y = salary, fill = salary)) +
  geom_bar(stat = "identity",
           lwd = 1, show.legend = T) +
  ggtitle("Pay by Location") +
  coord_polar() + 
  theme_minimal()
by_loc_p
loc_df
leaders_df
##________By Size___________
size_df <- ds_df %>% 
  group_by(company_size) %>% 
  summarise(salary = mean(salary_in_usd),
            n = n()) %>% 
  arrange(desc(salary)) %>% 
  filter(n >= 10)

by_size_p <- ggplot(size_df, aes(x = company_size, y = salary, fill = salary)) +
  geom_bar(stat = "identity",
           lwd = 1, show.legend = T) +
  ggtitle("Pay by Company Size") +
  coord_polar() + 
  theme_minimal()
plot(by_size_p)


##________By remote___________
remote_df <- ds_df %>% 
  group_by(remote_ratio) %>% 
  summarise(salary = mean(salary_in_usd),
            n = n()) %>% 
  arrange(desc(salary)) %>% 
  filter(n >= 10)

by_remote_p <- ggplot(remote_df, aes(x = remote_ratio, y = salary, fill = salary)) +
  geom_bar(stat = "identity",
           lwd = 1, show.legend = T) +
  ggtitle("Pay by Remote Ratio") +
  theme_minimal()
by_remote_p


##________By Residence___________
res_df <- ds_df %>% 
  group_by(employee_residence) %>% 
  summarise(salary = mean(salary_in_usd),
            n = n()) %>% 
  arrange(desc(salary)) %>% 
  filter(n >= 10)

by_res_p <- ggplot(res_df, aes(x = employee_residence, y = salary, fill = salary)) +
  geom_bar(stat = "identity",
           lwd = 1, show.legend = T) +
  ggtitle("Pay by Residence") +
  coord_polar() + 
  theme_minimal()
by_res_p


write_csv(loc_df, "loc.csv")
```

#### Is remote increasing by year?
```{r}
(remote_prop_df <- ds_df %>% 
  select(work_year, remote_ratio) %>% 
  group_by(work_year) %>% 
  summarise(remote_prop = mean(remote_ratio)))
```


#### Most lucrative year? Growing industry?
```{r}
(salary_prop_df <- ds_df %>% 
  select(work_year, salary_in_usd) %>% 
  group_by(work_year) %>% 
  summarise(salary_prop = mean(salary_in_usd)))
```


```{r}
library(caret)
train_i <- createDataPartition(dataset$Species, p=0.80, list=FALSE)
train_df <- ds_df[train_i,]
test_df <- ds_df[-train_i,]
control <- trainControl(method="cv", number=10)
metric <- "RMSE"
```

```{r}
num_df <- ds_df %>% 
  select_if(is.numeric)
correlationMatrix <- round(cor(num_df), 1)
correlationMatrix
head(correlationMatrix)
corrplot(correlationMatrix)

```



```{r}
set.seed(123)
ds_df
lm_m<- train(salary_in_usd ~. - salary_currency - salary, data=ds_df, method="lm",preProc = c("center", "scale", "nzv"), metric=metric, trControl=control)

knn_m <- train(salary_in_usd ~. - salary_currency - salary, data=ds_df, method="knn",preProc = c("center", "scale", "nzv"), metric=metric, trControl=control)

svm_m <- train(salary_in_usd ~. - salary_currency - salary, data=ds_df, method="svmRadial",preProc = c("center", "scale", "nzv"), metric=metric, trControl=control)

rf_m <- train(salary_in_usd ~. - salary_currency - salary, data=ds_df, method="rf", preProc = c("center", "scale", "nzv"), metric=metric, trControl=control)


model <- train(salary_in_usd ~. - salary_currency - salary, data=ds_df, 
               method = "nnet", metric = metric,
               tuneGrid=expand.grid(.decay = c(0.5, 0.1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10),.size = c(3, 5, 10, 20)),
               trControl = control,preProc = c("center", "scale", "nzv"),
               linout = TRUE)

results <- resamples(list(lm=lm_m, knn=knn_m, svm=svm_m, rf=rf_m, neural = model))
summary(results)
dotplot(results)

predict(fit.svm, ds_df)
ds_df$salary_in_usd
summary(lm_m)
svm_Imp <- varImp(svm_m)[-3.]
svm_Imp


df <- data.frame(svm_Imp$importance)
index <- rownames(df) %in% rownames(df)[!str_detect(rownames(df), "\\`")]
names <- rownames(df)[index]
df2 <- df[index,]
df3 <- data.frame(variable = names,
           importance = df2)
df3$variable <- factor(df3$variable)
df3 <- df3 %>% 
  arrange(desc(importance)) 
df3 <- df3[-c(3,10),]

df3$variable <- as.character(df3$variable)
df3$variable
variable_imp <- ggplot(data = df3,
       aes(reorder(variable, importance,sum), importance)) + 
  geom_col(aes(fill = importance)) + 
  ggtitle("Variable Importance") +
  scale_fill_gradient2(low = "#ffc3a0",
                       high = "#ffafbd") +
  theme_fivethirtyeight() +
  theme(plot.title = element_text(size = 15,
                                  hjust = 0.5),
        text=element_text(size=10)) +
  theme(axis.title=element_text()) +
  ylab("Importance") +
  xlab(NULL) +
  coord_flip()
variable_imp
```

```{r}
m1 <- lm(salary_in_usd ~ company_location + work_year + experience_level + employment_type + job_title + remote_ratio + company_size + employee_residence, data = ds_df)

testing_data <- ds_df %>% 
  select(-c(salary_currency, salary, salary_in_usd))

mean((predict(m1, testing_data) - ds_df$salary_in_usd)^2)

varImp(fit.rf)
varImp(model)
```


